using GeneFlow.ApiNet2.Domain.Identity;
using GeneFlow.ApiNet2.Domain.Studies;
using GeneFlow.ApiNet2.Domain.Studies.Entities;

namespace GeneFlow.ApiNet2.Tests.Domain.Studies.Entities;

/// <summary>
/// Unit tests for the StudyView entity.
/// </summary>
public class StudyViewTests
{
    private static StudyId CreateStudyId(long value = 1) => new(value);
    private static UserId CreateUserId(long value = 1) => new(value);

    #region CreateForUser

    [Fact]
    public void CreateForUser_WithValidData_ShouldReturnView()
    {
        // Arrange
        var studyId = CreateStudyId(42);
        var userId = CreateUserId(99);
        const string userAgent = "Mozilla/5.0";

        // Act
        var view = StudyView.CreateForUser(studyId, userId, userAgent);

        // Assert
        view.Should().NotBeNull();
        view.StudyId.Should().Be(studyId);
        view.UserId.Should().Be(userId);
        view.UserAgent.Should().Be(userAgent);
        view.IpHash.Should().BeNull();
    }

    [Fact]
    public void CreateForUser_ShouldSetViewedAtToNow()
    {
        // Arrange
        var studyId = CreateStudyId();
        var userId = CreateUserId();
        var beforeCreate = DateTime.UtcNow;

        // Act
        var view = StudyView.CreateForUser(studyId, userId, null);

        // Assert
        view.ViewedAt.Should().BeOnOrAfter(beforeCreate);
        view.ViewedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }

    [Fact]
    public void CreateForUser_WithNullUserAgent_ShouldCreateView()
    {
        // Arrange
        var studyId = CreateStudyId();
        var userId = CreateUserId();

        // Act
        var view = StudyView.CreateForUser(studyId, userId, null);

        // Assert
        view.UserAgent.Should().BeNull();
    }

    #endregion

    #region CreateForAnonymous

    [Fact]
    public void CreateForAnonymous_WithValidData_ShouldReturnView()
    {
        // Arrange
        var studyId = CreateStudyId(42);
        const string ipHash = "abc123def456";
        const string userAgent = "Mozilla/5.0";

        // Act
        var view = StudyView.CreateForAnonymous(studyId, ipHash, userAgent);

        // Assert
        view.Should().NotBeNull();
        view.StudyId.Should().Be(studyId);
        view.UserId.Should().BeNull();
        view.IpHash.Should().Be(ipHash);
        view.UserAgent.Should().Be(userAgent);
    }

    [Fact]
    public void CreateForAnonymous_ShouldSetViewedAtToNow()
    {
        // Arrange
        var studyId = CreateStudyId();
        var beforeCreate = DateTime.UtcNow;

        // Act
        var view = StudyView.CreateForAnonymous(studyId, "hash", null);

        // Assert
        view.ViewedAt.Should().BeOnOrAfter(beforeCreate);
    }

    [Fact]
    public void CreateForAnonymous_ShouldHaveNullUserId()
    {
        // Arrange & Act
        var view = StudyView.CreateForAnonymous(CreateStudyId(), "hash", null);

        // Assert
        view.UserId.Should().BeNull();
    }

    #endregion

    #region UserAgent Truncation

    [Fact]
    public void Create_WithLongUserAgent_ShouldTruncateTo500Chars()
    {
        // Arrange
        var studyId = CreateStudyId();
        var userId = CreateUserId();
        var longUserAgent = new string('a', 600);

        // Act
        var view = StudyView.CreateForUser(studyId, userId, longUserAgent);

        // Assert
        view.UserAgent.Should().HaveLength(500);
    }

    [Fact]
    public void Create_WithExactly500CharUserAgent_ShouldNotTruncate()
    {
        // Arrange
        var studyId = CreateStudyId();
        var userId = CreateUserId();
        var userAgent = new string('a', 500);

        // Act
        var view = StudyView.CreateForUser(studyId, userId, userAgent);

        // Assert
        view.UserAgent.Should().HaveLength(500);
    }

    [Fact]
    public void Create_WithShortUserAgent_ShouldNotTruncate()
    {
        // Arrange
        var studyId = CreateStudyId();
        var userId = CreateUserId();
        const string userAgent = "Mozilla/5.0";

        // Act
        var view = StudyView.CreateForUser(studyId, userId, userAgent);

        // Assert
        view.UserAgent.Should().Be(userAgent);
    }

    #endregion

    #region Id

    [Fact]
    public void Create_ShouldHaveDefaultIdZero()
    {
        // Arrange & Act
        var view = StudyView.CreateForUser(CreateStudyId(), CreateUserId(), null);

        // Assert
        // Note: The ID is set to 0 and will be auto-generated by the database
        view.Id.Should().Be(0);
    }

    #endregion

    #region Distinction Between User and Anonymous Views

    [Fact]
    public void UserView_ShouldHaveUserIdAndNoIpHash()
    {
        // Act
        var view = StudyView.CreateForUser(CreateStudyId(), CreateUserId(42), "agent");

        // Assert
        view.UserId.Should().NotBeNull();
        view.UserId!.Value.Should().Be(42);
        view.IpHash.Should().BeNull();
    }

    [Fact]
    public void AnonymousView_ShouldHaveIpHashAndNoUserId()
    {
        // Act
        var view = StudyView.CreateForAnonymous(CreateStudyId(), "hash123", "agent");

        // Assert
        view.UserId.Should().BeNull();
        view.IpHash.Should().Be("hash123");
    }

    #endregion
}
