// <auto-generated />
using System;
using System.Text.Json;
using GeneFlow.ApiNet2.Infrastructure.Traces.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Traces.Persistence.Migrations
{
    [DbContext(typeof(TraceContext))]
    [Migration("20260421000950_InitialTraces")]
    partial class InitialTraces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("traces")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Traces.Trace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failuREDACTED");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<bool>("HasChromatogramData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_chromatogram_data");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.ToTable("traces", "traces");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Traces.Trace", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.QualityMetrics", "QualityMetrics", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageQualityScore")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("average_quality_score");

                            b1.Property<decimal>("GcContentPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("gc_content_percentage");

                            b1.Property<decimal>("QualityAboveQ20Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("quality_above_q20_percentage");

                            b1.Property<decimal>("QualityAboveQ30Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("quality_above_q30_percentage");

                            b1.Property<int>("TotalBases")
                                .HasColumnType("integer")
                                .HasColumnName("total_bases");

                            b1.Property<int>("TrimmedLength")
                                .HasColumnType("integer")
                                .HasColumnName("trimmed_length");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "traces");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "traces");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceFile", "File", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("checksum");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_bytes");

                            b1.Property<string>("StoragePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("storage_path");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "traces");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "traces");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TrimRegion", "TrimRegion", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("trim_algorithm");

                            b1.Property<int>("End3Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_end_3_prime");

                            b1.Property<int>("End5Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_end_5_prime");

                            b1.Property<int>("Start3Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_start_3_prime");

                            b1.Property<int>("Start5Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_start_5_prime");

                            b1.Property<DateTime>("TrimmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("trimmed_at");

                            b1.Property<string>("TrimmedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("trimmed_by");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "traces");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Traces.Entities.SequenceEdit", "Edits", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("EditType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("edit_type");

                            b1.Property<DateTime>("EditedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("edited_at");

                            b1.Property<string>("EditedBy")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("edited_by");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("is_active");

                            b1.Property<char?>("NewBase")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("new_base");

                            b1.Property<char?>("OriginalBase")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("original_base");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid?>("trace_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("trace_id", "Position");

                            b1.ToTable("sequence_edits", "traces");

                            b1.WithOwner()
                                .HasForeignKey("trace_id");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Traces.Entities.TraceAnnotation", "Annotations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("color");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<int>("EndPosition")
                                .HasColumnType("integer")
                                .HasColumnName("end_position");

                            b1.Property<bool>("IsShared")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_shared");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<JsonDocument>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("modified_by");

                            b1.Property<int>("StartPosition")
                                .HasColumnType("integer")
                                .HasColumnName("start_position");

                            b1.Property<string>("Strand")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("strand");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<Guid?>("trace_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("trace_id", "IsShared");

                            b1.HasIndex("trace_id", "StartPosition", "EndPosition");

                            b1.ToTable("trace_annotations", "traces");

                            b1.WithOwner()
                                .HasForeignKey("trace_id");
                        });

                    b.Navigation("Annotations");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Edits");

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("QualityMetrics");

                    b.Navigation("TrimRegion");
                });
#pragma warning restore 612, 618
        }
    }
}
