// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Activity.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Activity.Persistence.Migrations
{
    [DbContext(typeof(ActivityContext))]
    [Migration("20260603215628_Phase1_Activity_AddActivityEventTable")]
    partial class Phase1_Activity_AddActivityEventTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("activity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Activity.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("object_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceEventType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_event_type");

                    b.Property<string>("SourceMessageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_message_id");

                    b.Property<string>("StudyId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_id");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verb");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_activity_events_source_message_id")
                        .HasFilter("source_message_id IS NOT NULL");

                    b.HasIndex("OccurredAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_activity_events_occurred_at_id");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_activity_events_actor_occurred_at_id");

                    b.HasIndex("StudyId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_activity_events_study_occurred_at_id");

                    b.ToTable("activity_events", "activity");
                });
#pragma warning restore 612, 618
        }
    }
}
