// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Studies.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Studies.Persistence.Migrations
{
    [DbContext(typeof(StudyContext))]
    [Migration("20260606205055_AddStudyOwnerType")]
    partial class AddStudyOwnerType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("studies")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyInvitation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("invited_by");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("StudyId", "Email");

                    b.ToTable("study_invitations", "studies");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyStar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("StarredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starred_at");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.HasIndex("UserId");

                    b.HasIndex("StudyId", "UserId")
                        .IsUnique();

                    b.ToTable("study_stars", "studies");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.HasIndex("StudyId", "ViewedAt");

                    b.HasIndex("StudyId", "IpHash", "ViewedAt");

                    b.ToTable("study_views", "studies");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Study", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("User")
                        .HasColumnName("owner_type");

                    b.Property<string>("PrincipalInvestigator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("principal_investigator");

                    b.Property<string>("ReadmeMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("readme_markdown");

                    b.Property<string>("ResearchField")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("research_field");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string[]>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ResearchField");

                    b.HasIndex("Status");

                    b.ToTable("studies", "studies");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Study", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyDescription", "Description", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("description");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyMetrics", "Metrics", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<int>("StarsCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("stars_count");

                            b1.Property<int>("ViewsCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("views_count");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudySettings", "Settings", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("AllowDataDownload")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("allow_data_download");

                            b1.Property<bool>("AllowPublicComments")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("allow_public_comments");

                            b1.Property<bool>("RequireApprovalToJoin")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("requiREDACTED");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyTitle", "Title", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("InvitedBy")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("invited_by");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("user_id");

                            b1.Property<string>("study_id")
                                .IsRequired()
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("study_id", "UserId")
                                .IsUnique();

                            b1.ToTable("study_members", "studies");

                            b1.WithOwner()
                                .HasForeignKey("study_id");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyPaper", "Papers", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("id");

                            b1.Property<string>("Abstract")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("abstract");

                            b1.Property<string>("Authors")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("authors");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("Doi")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("doi");

                            b1.Property<string>("FileId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("file_id");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long?>("FileSizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size_bytes");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("Journal")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("journal");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("modified_by");

                            b1.Property<int?>("PublicationYear")
                                .HasColumnType("integer")
                                .HasColumnName("publication_year");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("title");

                            b1.Property<string>("study_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("study_id");

                            b1.ToTable("study_papers", "studies");

                            b1.WithOwner()
                                .HasForeignKey("study_id");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("Metrics")
                        .IsRequired();

                    b.Navigation("Papers");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
