// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Pipelines.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Pipelines.Persistence.Migrations
{
    [DbContext(typeof(PipelineContext))]
    [Migration("20260427214947_FixStepExecutionIdMapping")]
    partial class FixStepExecutionIdMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pipelines")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_steps");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pipeline_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.HasIndex("Status");

                    b.HasIndex("TraceId");

                    b.HasIndex("TraceId", "Status");

                    b.ToTable("pipeline_executions", "pipelines");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Pipeline", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modified_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.ToTable("pipelines", "pipelines");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineExecution", b =>
                {
                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Pipelines.Entities.StepExecution", "StepExecutions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<Guid>("PipelineStepId")
                                .HasColumnType("uuid")
                                .HasColumnName("pipeline_step_id");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<string>("ResultSummary")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("result_summary");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("step_type");

                            b1.Property<string>("execution_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("execution_id", "Order")
                                .IsUnique();

                            b1.ToTable("pipeline_step_executions", "pipelines");

                            b1.WithOwner()
                                .HasForeignKey("execution_id");
                        });

                    b.Navigation("StepExecutions");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Pipeline", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.PipelineDescription", "Description", b1 =>
                        {
                            b1.Property<string>("PipelineId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.HasKey("PipelineId");

                            b1.ToTable("pipelines", "pipelines");

                            b1.WithOwner()
                                .HasForeignKey("PipelineId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.PipelineName", "Name", b1 =>
                        {
                            b1.Property<string>("PipelineId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("PipelineId");

                            b1.HasIndex("Value");

                            b1.ToTable("pipelines", "pipelines");

                            b1.WithOwner()
                                .HasForeignKey("PipelineId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("is_enabled");

                            b1.Property<string>("Label")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("step_type");

                            b1.Property<string>("pipeline_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("pipeline_id", "Order")
                                .IsUnique();

                            b1.ToTable("pipeline_steps", "pipelines");

                            b1.WithOwner()
                                .HasForeignKey("pipeline_id");

                            b1.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.StepConfiguration", "Configuration", b2 =>
                                {
                                    b2.Property<Guid>("PipelineStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasDefaultValue("{}")
                                        .HasColumnName("configuration");

                                    b2.HasKey("PipelineStepId");

                                    b2.ToTable("pipeline_steps", "pipelines");

                                    b2.WithOwner()
                                        .HasForeignKey("PipelineStepId");
                                });

                            b1.Navigation("Configuration")
                                .IsRequired();
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
