// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Identity.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Identity.Persistence.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260406014506_InitialUserContext")]
    partial class InitialUserContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Identity.User", b =>
                {
                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.Entities.ExternalLogin", "_externalLogins", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("LinkedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("linked_at");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("provider");

                            b1.Property<string>("ProviderDisplayName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("provider_display_name");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("provider_key");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.HasIndex("Provider", "ProviderKey")
                                .IsUnique();

                            b1.ToTable("external_logins", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.AccountLockout", "Lockout", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<int>("FailedAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("failed_login_attempts");

                            b1.Property<DateTime?>("LockoutEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("lockout_end");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.EmailVerification", "EmailVerification", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("email_verified");

                            b1.Property<string>("Token")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("email_verification_token");

                            b1.Property<DateTime?>("TokenExpiry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("email_verification_token_expiry");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.PasswordReset", "PasswordReset", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Token")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("password_reset_token");

                            b1.Property<DateTime?>("TokenExpiry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("password_reset_token_expiry");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.RefreshToken", "_refreshTokens", b1 =>
                        {
                            b1.Property<string>("Token")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("token");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<bool>("IsRevoked")
                                .HasColumnType("boolean")
                                .HasColumnName("is_revoked");

                            b1.Property<string>("ReplacedByToken")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("replaced_by_token");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Token");

                            b1.HasIndex("Token");

                            b1.HasIndex("UserId");

                            b1.ToTable("refresh_tokens", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.TwoFactorAuth", "TwoFactorAuth", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("two_factor_enabled");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.TwoFactorSecret", "TotpSecret", b2 =>
                                {
                                    b2.Property<string>("TwoFactorAuthUserId")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("totp_secret_created_at");

                                    b2.Property<string>("EncryptedSecret")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)")
                                        .HasColumnName("totp_secret");

                                    b2.HasKey("TwoFactorAuthUserId");

                                    b2.ToTable("users", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("TwoFactorAuthUserId");
                                });

                            b1.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.Entities.TwoFactorCode", "Codes", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(6)
                                        .HasColumnType("character varying(6)")
                                        .HasColumnName("code");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<DateTime>("ExpiresAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("expires_at");

                                    b2.Property<bool>("IsUsed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_used");

                                    b2.Property<DateTime?>("UsedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("used_at");

                                    b2.Property<string>("UserId")
                                        .HasColumnType("character varying(10)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("two_factor_codes", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("Codes");

                            b1.Navigation("TotpSecret");
                        });

                    b.Navigation("EmailVerification")
                        .IsRequired();

                    b.Navigation("Lockout")
                        .IsRequired();

                    b.Navigation("PasswordReset")
                        .IsRequired();

                    b.Navigation("TwoFactorAuth")
                        .IsRequired();

                    b.Navigation("_externalLogins");

                    b.Navigation("_refreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
