// <auto-generated />
using System;
using System.Text.Json;
using GeneFlow.ApiNet2.Infrastructure.Identity.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Identity.Persistence.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260427191401_AddPipelines")]
    partial class AddPipelines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_steps");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pipeline_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.HasIndex("Status");

                    b.HasIndex("TraceId");

                    b.HasIndex("TraceId", "Status");

                    b.ToTable("pipeline_executions", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Pipeline", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modified_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.ToTable("pipelines", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Plans.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDefault");

                    b.ToTable("plans", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Profiles.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("ResearchField")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("research_field");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResearchField");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyInvitation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("invited_by");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("StudyId", "Email");

                    b.ToTable("study_invitations", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyStar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("StarredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starred_at");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.HasIndex("UserId");

                    b.HasIndex("StudyId", "UserId")
                        .IsUnique();

                    b.ToTable("study_stars", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.HasIndex("StudyId", "ViewedAt");

                    b.HasIndex("StudyId", "IpHash", "ViewedAt");

                    b.ToTable("study_views", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Study", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_id");

                    b.Property<string>("PrincipalInvestigator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("principal_investigator");

                    b.Property<string>("ResearchField")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("research_field");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ResearchField");

                    b.HasIndex("Status");

                    b.ToTable("studies", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<int>("BillingCycle")
                        .HasColumnType("integer")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("plan_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("subscriptions", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Traces.Trace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failuREDACTED");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<bool>("HasChromatogramData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_chromatogram_data");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.HasIndex("Status");

                    b.HasIndex("StudyId");

                    b.ToTable("traces", "identity");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Identity.User", b =>
                {
                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.Entities.ExternalLogin", "_externalLogins", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("LinkedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("linked_at");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("provider");

                            b1.Property<string>("ProviderDisplayName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("provider_display_name");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("provider_key");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.HasIndex("Provider", "ProviderKey")
                                .IsUnique();

                            b1.ToTable("external_logins", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.AccountLockout", "Lockout", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<int>("FailedAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("failed_login_attempts");

                            b1.Property<DateTime?>("LockoutEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("lockout_end");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.EmailVerification", "EmailVerification", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("email_verified");

                            b1.Property<string>("Token")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("email_verification_token");

                            b1.Property<DateTime?>("TokenExpiry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("email_verification_token_expiry");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.PasswordReset", "PasswordReset", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Token")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("password_reset_token");

                            b1.Property<DateTime?>("TokenExpiry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("password_reset_token_expiry");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.RefreshToken", "_refreshTokens", b1 =>
                        {
                            b1.Property<string>("Token")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("token");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<bool>("IsRevoked")
                                .HasColumnType("boolean")
                                .HasColumnName("is_revoked");

                            b1.Property<string>("ReplacedByToken")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("replaced_by_token");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Token");

                            b1.HasIndex("Token");

                            b1.HasIndex("UserId");

                            b1.ToTable("refresh_tokens", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.TwoFactorAuth", "TwoFactorAuth", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("two_factor_enabled");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("GeneFlow.ApiNet2.Domain.Identity.ValueObjects.TwoFactorSecret", "TotpSecret", b2 =>
                                {
                                    b2.Property<string>("TwoFactorAuthUserId")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("totp_secret_created_at");

                                    b2.Property<string>("EncryptedSecret")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)")
                                        .HasColumnName("totp_secret");

                                    b2.HasKey("TwoFactorAuthUserId");

                                    b2.ToTable("users", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("TwoFactorAuthUserId");
                                });

                            b1.OwnsMany("GeneFlow.ApiNet2.Domain.Identity.Entities.TwoFactorCode", "Codes", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(6)
                                        .HasColumnType("character varying(6)")
                                        .HasColumnName("code");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<DateTime>("ExpiresAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("expires_at");

                                    b2.Property<bool>("IsUsed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_used");

                                    b2.Property<DateTime?>("UsedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("used_at");

                                    b2.Property<string>("UserId")
                                        .HasColumnType("character varying(10)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("two_factor_codes", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("Codes");

                            b1.Navigation("TotpSecret");
                        });

                    b.Navigation("EmailVerification")
                        .IsRequired();

                    b.Navigation("Lockout")
                        .IsRequired();

                    b.Navigation("PasswordReset")
                        .IsRequired();

                    b.Navigation("TwoFactorAuth")
                        .IsRequired();

                    b.Navigation("_externalLogins");

                    b.Navigation("_refreshTokens");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineExecution", b =>
                {
                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Pipelines.Entities.StepExecution", "StepExecutions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<Guid>("PipelineStepId")
                                .HasColumnType("uuid")
                                .HasColumnName("pipeline_step_id");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<string>("ResultSummary")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("result_summary");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("step_type");

                            b1.Property<string>("execution_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("execution_id", "Order")
                                .IsUnique();

                            b1.ToTable("pipeline_step_executions", "identity");

                            b1.WithOwner()
                                .HasForeignKey("execution_id");
                        });

                    b.Navigation("StepExecutions");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Pipelines.Pipeline", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.PipelineDescription", "Description", b1 =>
                        {
                            b1.Property<string>("PipelineId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.HasKey("PipelineId");

                            b1.ToTable("pipelines", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PipelineId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.PipelineName", "Name", b1 =>
                        {
                            b1.Property<string>("PipelineId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("PipelineId");

                            b1.HasIndex("Value");

                            b1.ToTable("pipelines", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PipelineId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Pipelines.Entities.PipelineStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("is_enabled");

                            b1.Property<string>("Label")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("step_type");

                            b1.Property<string>("pipeline_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("pipeline_id", "Order")
                                .IsUnique();

                            b1.ToTable("pipeline_steps", "identity");

                            b1.WithOwner()
                                .HasForeignKey("pipeline_id");

                            b1.OwnsOne("GeneFlow.ApiNet2.Domain.Pipelines.ValueObjects.StepConfiguration", "Configuration", b2 =>
                                {
                                    b2.Property<Guid>("PipelineStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasDefaultValue("{}")
                                        .HasColumnName("configuration");

                                    b2.HasKey("PipelineStepId");

                                    b2.ToTable("pipeline_steps", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("PipelineStepId");
                                });

                            b1.Navigation("Configuration")
                                .IsRequired();
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Plans.Plan", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanLimits", "Limits", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<int>("MaxMembersPerStudy")
                                .HasColumnType("integer")
                                .HasColumnName("max_members_per_study");

                            b1.Property<int>("MaxStudies")
                                .HasColumnType("integer")
                                .HasColumnName("max_studies");

                            b1.Property<int>("MaxTracesPerMonth")
                                .HasColumnType("integer")
                                .HasColumnName("max_traces_per_month");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanName", "Name", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("PlanId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("plans", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanPricing", "Pricing", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<decimal>("AnnualPrice")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("annual_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("MonthlyPrice")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("monthly_price");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Plans.Enumerations.PlanFeature", "Features", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("featuREDACTED");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("featuREDACTED");

                            b1.Property<string>("plan_id")
                                .IsRequired()
                                .HasColumnType("character varying(9)");

                            b1.HasKey("id");

                            b1.HasIndex("plan_id");

                            b1.ToTable("plan_features", "identity");

                            b1.WithOwner()
                                .HasForeignKey("plan_id");
                        });

                    b.Navigation("Features");

                    b.Navigation("Limits")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Profiles.Profile", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Bio", "Bio", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("bio");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Institution", "Institution", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Department")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("institution_department");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("institution_name");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ProfessionalRole", "ProfessionalRole", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("professional_role");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ProfilePhoto", "Photo", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("photo_size_bytes");

                            b1.Property<string>("ThumbnailUrl")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("photo_thumbnail_url");

                            b1.Property<string>("Url")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("photo_url");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ResearchIdentifiers", "ResearchIdentifiers", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("OrcidId")
                                .HasMaxLength(19)
                                .HasColumnType("character varying(19)")
                                .HasColumnName("orcid_id");

                            b1.Property<string>("Website")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("website");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Bio")
                        .IsRequired();

                    b.Navigation("Institution")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Photo")
                        .IsRequired();

                    b.Navigation("ProfessionalRole")
                        .IsRequired();

                    b.Navigation("ResearchIdentifiers")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Studies.Study", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyDescription", "Description", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("description");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "identity");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyMetrics", "Metrics", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<int>("StarsCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("stars_count");

                            b1.Property<int>("ViewsCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("views_count");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "identity");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudySettings", "Settings", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<bool>("AllowDataDownload")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("allow_data_download");

                            b1.Property<bool>("AllowPublicComments")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("allow_public_comments");

                            b1.Property<bool>("RequireApprovalToJoin")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("requiREDACTED");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "identity");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Studies.ValueObjects.StudyTitle", "Title", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");

                            b1.HasKey("StudyId");

                            b1.ToTable("studies", "identity");

                            b1.WithOwner()
                                .HasForeignKey("StudyId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("InvitedBy")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("invited_by");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("user_id");

                            b1.Property<string>("study_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("study_id", "UserId")
                                .IsUnique();

                            b1.ToTable("study_members", "identity");

                            b1.WithOwner()
                                .HasForeignKey("study_id");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Studies.Entities.StudyPaper", "Papers", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("id");

                            b1.Property<string>("Abstract")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("abstract");

                            b1.Property<string>("Authors")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("authors");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("Doi")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("doi");

                            b1.Property<string>("FileId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("file_id");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long?>("FileSizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size_bytes");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("Journal")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("journal");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("modified_by");

                            b1.Property<int?>("PublicationYear")
                                .HasColumnType("integer")
                                .HasColumnName("publication_year");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("title");

                            b1.Property<string>("study_id")
                                .HasColumnType("character varying(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("study_id");

                            b1.ToTable("study_papers", "identity");

                            b1.WithOwner()
                                .HasForeignKey("study_id");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("Metrics")
                        .IsRequired();

                    b.Navigation("Papers");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Subscriptions.Subscription", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Subscriptions.ValueObjects.SubscriptionPeriod", "CurrentPeriod", b1 =>
                        {
                            b1.Property<string>("SubscriptionId")
                                .HasColumnType("character varying(9)");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscriptions", "identity");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("CurrentPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Traces.Trace", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.QualityMetrics", "QualityMetrics", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageQualityScore")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("average_quality_score");

                            b1.Property<decimal>("GcContentPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("gc_content_percentage");

                            b1.Property<decimal>("QualityAboveQ20Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("quality_above_q20_percentage");

                            b1.Property<decimal>("QualityAboveQ30Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("quality_above_q30_percentage");

                            b1.Property<int>("TotalBases")
                                .HasColumnType("integer")
                                .HasColumnName("total_bases");

                            b1.Property<int>("TrimmedLength")
                                .HasColumnType("integer")
                                .HasColumnName("trimmed_length");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceFile", "File", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("checksum");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_bytes");

                            b1.Property<string>("StoragePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("storage_path");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TraceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Traces.ValueObjects.TrimRegion", "TrimRegion", b1 =>
                        {
                            b1.Property<Guid>("TraceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("trim_algorithm");

                            b1.Property<int>("End3Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_end_3_prime");

                            b1.Property<int>("End5Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_end_5_prime");

                            b1.Property<int>("Start3Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_start_3_prime");

                            b1.Property<int>("Start5Prime")
                                .HasColumnType("integer")
                                .HasColumnName("trim_start_5_prime");

                            b1.Property<DateTime>("TrimmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("trimmed_at");

                            b1.Property<string>("TrimmedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("trimmed_by");

                            b1.HasKey("TraceId");

                            b1.ToTable("traces", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TraceId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Traces.Entities.SequenceEdit", "Edits", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("EditType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("edit_type");

                            b1.Property<DateTime>("EditedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("edited_at");

                            b1.Property<string>("EditedBy")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("edited_by");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("is_active");

                            b1.Property<char?>("NewBase")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("new_base");

                            b1.Property<char?>("OriginalBase")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("original_base");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid?>("trace_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("trace_id", "Position");

                            b1.ToTable("sequence_edits", "identity");

                            b1.WithOwner()
                                .HasForeignKey("trace_id");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Traces.Entities.TraceAnnotation", "Annotations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("color");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<int>("EndPosition")
                                .HasColumnType("integer")
                                .HasColumnName("end_position");

                            b1.Property<bool>("IsShared")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_shared");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<JsonDocument>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("modified_by");

                            b1.Property<int>("StartPosition")
                                .HasColumnType("integer")
                                .HasColumnName("start_position");

                            b1.Property<string>("Strand")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("strand");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<Guid?>("trace_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("trace_id", "IsShared");

                            b1.HasIndex("trace_id", "StartPosition", "EndPosition");

                            b1.ToTable("trace_annotations", "identity");

                            b1.WithOwner()
                                .HasForeignKey("trace_id");
                        });

                    b.Navigation("Annotations");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Edits");

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("QualityMetrics");

                    b.Navigation("TrimRegion");
                });
#pragma warning restore 612, 618
        }
    }
}
