using GeneFlow.ApiNet2.Application.Traces.DTOs;
using GeneFlow.ApiNet2.Application.Traces.Mappings;
using GeneFlow.ApiNet2.Domain.Identity;
using GeneFlow.ApiNet2.Domain.Studies;
using GeneFlow.ApiNet2.Domain.Traces;
using GeneFlow.ApiNet2.Domain.Traces.Enumerations;
using GeneFlow.ApiNet2.Domain.Traces.ValueObjects;
using GeneFlow.ApiNet2.SharedKernel.Application.CQRS;
using GeneFlow.ApiNet2.SharedKernel.Domain.Results;
using GeneFlow.ApiNet2.SharedKernel.Infrastructure;

namespace GeneFlow.ApiNet2.Application.Traces.Commands.UploadTrace;

/// <summary>
/// Handler for UploadTraceCommand.
/// </summary>
public sealed class UploadTraceCommandHandler
    : ICommandHandler<UploadTraceCommand, Result<TraceDto>>
{
    private readonly ITraceUnitOfWork _unitOfWork;
    private readonly IJobPublisher _jobPublisher;

    public UploadTraceCommandHandler(
        ITraceUnitOfWork unitOfWork,
        IJobPublisher jobPublisher)
    {
        _unitOfWork = unitOfWork;
        _jobPublisher = jobPublisher;
    }

    public async Task<Result<TraceDto>> Handle(
        UploadTraceCommand request,
        CancellationToken cancellationToken)
    {
        // Parse user ID
        if (!UserId.TryParse(request.UserId, out var userId) || userId is null)
            return Result.Failure<TraceDto>(TraceErrors.InvalidUserId);

        // Parse study ID
        if (!StudyId.TryParse(request.StudyId, out var studyId) || studyId is null)
            return Result.Failure<TraceDto>(TraceErrors.InvalidStudyId);

        // Create name value object
        var nameResult = TraceName.Create(request.Name);
        if (nameResult.IsFailure)
            return Result.Failure<TraceDto>(nameResult.Error);

        // Create description value object
        var descriptionResult = TraceDescription.Create(request.Description);
        if (descriptionResult.IsFailure)
            return Result.Failure<TraceDto>(descriptionResult.Error);

        // Create file value object
        var fileResult = TraceFile.Create(
            request.FileName,
            request.ContentType,
            request.StoragePath,
            request.SizeBytes,
            request.Checksum);
        if (fileResult.IsFailure)
            return Result.Failure<TraceDto>(fileResult.Error);

        // Determine format from file extension
        var extension = Path.GetExtension(request.FileName);
        var format = TraceFormat.FromExtension(extension);
        if (format is null)
            return Result.Failure<TraceDto>(TraceErrors.UnsupportedFormat);

        // Parse trace ID from request (generated by endpoint)
        if (!TraceId.TryParse(request.TraceId, out var traceId) || traceId is null)
            return Result.Failure<TraceDto>(TraceErrors.InvalidTraceId);

        // Create trace
        var traceResult = Trace.Create(
            traceId,
            studyId,
            userId,
            nameResult.Value,
            descriptionResult.Value,
            fileResult.Value,
            format);

        if (traceResult.IsFailure)
            return Result.Failure<TraceDto>(traceResult.Error);

        var trace = traceResult.Value;

        // Persist
        await _unitOfWork.Traces.AddAsync(trace, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        // Publish job to Analysis worker for processing
        await _jobPublisher.PublishTraceJobAsync(new TraceProcessingJob(
            TraceId: trace.Id.ToString(),
            StudyId: trace.StudyId.ToString(),
            FileName: request.FileName,
            StoragePath: request.StoragePath,
            Format: format.Name
        ), cancellationToken);

        return Result.Success(trace.ToDto());
    }
}
