// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Profiles.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Profiles.Persistence.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20260606090105_AddPinnedStudies")]
    partial class AddPinnedStudies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profiles")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Profiles.Entities.PinnedStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTime>("PinnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_at");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("study_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StudyId")
                        .IsUnique();

                    b.ToTable("pinned_studies", "profiles");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Profiles.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("ResearchField")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("research_field");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResearchField");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", "profiles");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Profiles.Profile", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Bio", "Bio", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("bio");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Institution", "Institution", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Department")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("institution_department");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("institution_name");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ProfessionalRole", "ProfessionalRole", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("professional_role");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ProfilePhoto", "Photo", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("photo_size_bytes");

                            b1.Property<string>("ThumbnailUrl")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("photo_thumbnail_url");

                            b1.Property<string>("Url")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("photo_url");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Profiles.ValueObjects.ResearchIdentifiers", "ResearchIdentifiers", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("OrcidId")
                                .HasMaxLength(19)
                                .HasColumnType("character varying(19)")
                                .HasColumnName("orcid_id");

                            b1.Property<string>("Website")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("website");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles", "profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Bio")
                        .IsRequired();

                    b.Navigation("Institution")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Photo")
                        .IsRequired();

                    b.Navigation("ProfessionalRole")
                        .IsRequired();

                    b.Navigation("ResearchIdentifiers")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
