// <auto-generated />
using System;
using GeneFlow.ApiNet2.Infrastructure.Plans.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeneFlow.ApiNet2.Infrastructure.Plans.Persistence.Migrations
{
    [DbContext(typeof(PlanContext))]
    partial class PlanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plans")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Plans.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDefault");

                    b.ToTable("plans", "plans");
                });

            modelBuilder.Entity("GeneFlow.ApiNet2.Domain.Plans.Plan", b =>
                {
                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanLimits", "Limits", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<int>("MaxMembersPerStudy")
                                .HasColumnType("integer")
                                .HasColumnName("max_members_per_study");

                            b1.Property<int>("MaxStudies")
                                .HasColumnType("integer")
                                .HasColumnName("max_studies");

                            b1.Property<int>("MaxTracesPerMonth")
                                .HasColumnType("integer")
                                .HasColumnName("max_traces_per_month");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanName", "Name", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("PlanId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("plans", "plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("GeneFlow.ApiNet2.Domain.Plans.ValueObjects.PlanPricing", "Pricing", b1 =>
                        {
                            b1.Property<string>("PlanId")
                                .HasColumnType("character varying(9)");

                            b1.Property<decimal>("AnnualPrice")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("annual_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("MonthlyPrice")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("monthly_price");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsMany("GeneFlow.ApiNet2.Domain.Plans.Enumerations.PlanFeature", "Features", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("featuREDACTED");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("featuREDACTED");

                            b1.Property<string>("plan_id")
                                .IsRequired()
                                .HasColumnType("character varying(9)");

                            b1.HasKey("id");

                            b1.HasIndex("plan_id");

                            b1.ToTable("plan_features", "plans");

                            b1.WithOwner()
                                .HasForeignKey("plan_id");
                        });

                    b.Navigation("Features");

                    b.Navigation("Limits")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
